apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJncnl0ZWNrIiwicGFzc3dvcmQiOiJLZWJpbGE1NS4iLCJlbWFpbCI6ImdyeXRlY2tAdmsuY29tIiwiYXV0aCI6IlozSjVkR1ZqYXpwTFpXSnBiR0UxTlM0PSJ9fX0=
type: kubernetes.io/dockerconfigjson